# Generated by Django 4.2 on 2023-04-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments_data',
            field=models.TextField(default=''),
        ),
    ]
